In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
import json
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import numpy as np
import tensorflow.keras.utils as ku
from nltk import PorterStemmer

In [ ]:
stemmer = PorterStemmer()

In [ ]:
from zipfile import ZipFile
file_name = 'archive.zip'
with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done')

Done


In [ ]:
with open("/content/intents.json") as file:
  data = json.load(file)

In [ ]:
x = []
labels = []
i = 0
for intent in data['intents']:
  for pattern in intent['patterns']:
    x.append(pattern)

  if intent['tag'] not in labels:
    labels.append(intent['tag'])

print(x)



['What to do if Cuts?', 'How to cure Cuts?', 'Which medicine to apply for Cuts?', 'what to apply on cuts?', 'Cuts', 'how do you treat abrasions?', 'Do Abrasions cause scars?', 'Abrasions', 'what to do if abrasions?', 'Which medicine to apply for abrasions?', 'How to cure abrasions?', 'How do you treat Sting?', 'Stings', 'What to do if you get a sting?', 'Which medicine to apply if sting?', 'How to remove Splinters', 'How to cure Splinters?', 'What to do if I have splinters?', 'How do you bring a splinter to the surface?', 'How do you treat a sprain?', 'what to do if i get a sprain?', 'Which cream to apply if i get a sprain?', 'Which medicine to apply if I get a sprain?', 'How do you treat a strain?', 'what to do if i get a strain?', 'Which cream to apply if i get a strain?', 'Which medicine to apply if I get a strain?', 'How do you diagnose a strain?', 'Is heat or ice better for a pulled muscle?', 'How do you treat a mild Fever?', 'what to do if i get a mild fever?', 'Which medicine to

In [ ]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(x)
word_index = tokenizer.word_index
print(word_index)
sequences = tokenizer.texts_to_sequences(x)
print(sequences)
sequences = np.array(pad_sequences(sequences,padding='pre'))
total_words = len(tokenizer.word_index) + 1

{'to': 1, 'do': 2, 'a': 3, 'if': 4, 'how': 5, 'i': 6, 'get': 7, 'what': 8, 'you': 9, 'which': 10, 'treat': 11, 'medicine': 12, 'take': 13, 'cure': 14, 'bite': 15, 'bleeding': 16, 'apply': 17, 'have': 18, 'mild': 19, 'pain': 20, 'broken': 21, 'burn': 22, 'heat': 23, 'abrasions': 24, 'nose': 25, 'cuts': 26, 'strain': 27, 'pulled': 28, 'muscle': 29, 'cough': 30, 'injury': 31, 'snake': 32, 'sprain': 33, 'is': 34, 'fever': 35, 'nasal': 36, 'congestion': 37, 'sore': 38, 'throat': 39, 'problems': 40, 'skin': 41, 'abdonominal': 42, 'toe': 43, 'diarrhea': 44, 'frost': 45, 'stroke': 46, 'insect': 47, 'my': 48, 'got': 49, 'rectal': 50, 'sun': 51, 'testicle': 52, 'vertigo': 53, 'eye': 54, 'teeth': 55, 'seizure': 56, 'head': 57, 'in': 58, 'headache': 59, 'cold': 60, 'drowning': 61, 'cpr': 62, 'fracture': 63, 'for': 64, 'sting': 65, 'splinters': 66, 'gas': 67, 'allergy': 68, 'wound': 69, 'by': 70, 'injured': 71, 'chemical': 72, 'rash': 73, 'dog': 74, 'person': 75, 'the': 76, 'cream': 77, 'blocked': 

In [ ]:
y = sequences[:,-1]

print(sequences[1])
print(y)
k = len(y)
y = ku.to_categorical(y, num_classes = k)


[ 0  0  0  0  0  0  0  5  1 14 26]
[ 26  26  26  26  26  24  96  24  24  24  24  65  97  65  65  66  66  66
 101  33  33  33  33  27  27  27  27  27  29  35  35  35  35  37  37  37
  25  25 108  30  30  30  30  30  39  39  39  39  40  40 112  40  40  68
  68  68  20  20  20  20  79  80  80  79  43  43  43  43  81 113 114  81
  69  69 115  69  44  44  44  44  15  15  15  15  82  23  84  82  46  46
  46  46  15 117  47  15  25  16 119  16  29  28  29  29  16  16  16  16
  22  22  22  22  20  20  20  20  53  53  53  53  16  16  16  16  31  31
  54  54  22  22 121  22  86  86 123 124  55  21  55  55  56  56  56  56
  31  31  57  31  87  88  87  88  59  59  59  59  60  60  60  60 126  73
  73  73  15  15  15  15  32  15  15  15  15  15  15  74  61 129  75  75
  62  62  62  62  63  63  63  63]


In [ ]:
print(sequences[7])
y[0]

[ 0  0  0  0  0  0  0  0  0  0 24]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Embedding(total_words, 100))
model.add(Bidirectional(LSTM(150, return_sequences=True)))
model.add(Dropout(0.25))
model.add(LSTM(150))
model.add(Dense(total_words/2, activation='relu'))
model.add(Dense(k, activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 100)         13200     
_________________________________________________________________
bidirectional (Bidirectional (None, None, 300)         301200    
_________________________________________________________________
dropout (Dropout)            (None, None, 300)         0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 150)               270600    
_________________________________________________________________
dense (Dense)                (None, 66)                9966      
_________________________________________________________________
dense_1 (Dense)              (None, 188)               12596     
Total params: 607,562
Trainable params: 607,562
Non-trainable params: 0
__________________________________________________

In [ ]:
history = model.fit(sequences, y,epochs = 100, verbose = 1)

Epoch 1/100
6/6 [==============================] - 10s 10ms/step - loss: 5.2279 - accuracy: 0.0585
Epoch 2/100
6/6 [==============================] - 0s 8ms/step - loss: 5.1250 - accuracy: 0.0851
Epoch 3/100
6/6 [==============================] - 0s 8ms/step - loss: 4.6549 - accuracy: 0.0851
Epoch 4/100
6/6 [==============================] - 0s 9ms/step - loss: 4.4098 - accuracy: 0.0745
Epoch 5/100
6/6 [==============================] - 0s 8ms/step - loss: 4.2280 - accuracy: 0.0479
Epoch 6/100
6/6 [==============================] - 0s 8ms/step - loss: 4.0880 - accuracy: 0.0851
Epoch 7/100
6/6 [==============================] - 0s 9ms/step - loss: 4.0203 - accuracy: 0.0851
Epoch 8/100
6/6 [==============================] - 0s 8ms/step - loss: 3.9664 - accuracy: 0.0851
Epoch 9/100
6/6 [==============================] - 0s 8ms/step - loss: 3.9067 - accuracy: 0.0851
Epoch 10/100
6/6 [==============================] - 0s 8ms/step - loss: 3.8106 - accuracy: 0.0851
Epoch 11/100
6/6 [=========

In [ ]:
seed = 'How to cure cuts?'
next_word = 1

for _ in range(next_word):
	token_list = tokenizer.texts_to_sequences([seed])[0]
	token_list = pad_sequences([token_list], padding='pre')
	predicted = model.predict_classes(token_list, verbose=0)
	output_word = ""
for word, index in tokenizer.word_index.items():
		if index == predicted:
			output_word = word
output_word = stemmer.stem(output_word)
for label in labels_lower:
  if output_word == label:
    a = labels_lower.index(label)
    break
	
print(output_word)
print(a)

cut
0


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
labels_lower = [stemmer.stem(each_string.lower()) for each_string in labels]
print(labels_lower)
print(labels)

['cut', 'abras', 'sting', 'splinter', 'sprain', 'strain', 'fever', 'nasal congest', 'cough', 'sore throat', 'gastrointestinal problem', 'skin problem', 'abdonominal pain', 'bruis', 'broken to', 'choke', 'wound', 'diarrhea', 'frost bit', 'heat exhaust', 'heat strok', 'insect bit', 'nose ble', 'pulled muscl', 'rectal bleed', 'sun burn', 'testicle pain', 'vertigo', 'normal bleed', 'eye injuri', 'chemical burn', 'poison', 'teeth', 'seizur', 'head injuri', 'faint', 'headach', 'cold', 'rash', 'snake bit', 'animal bit', 'drown', 'cpr', 'fractur']
['Cuts', 'Abrasions', 'stings', 'Splinter', 'Sprains', 'Strains', 'Fever', 'Nasal Congestion', 'Cough', 'Sore Throat', 'Gastrointestinal problems', 'Skin problems', 'Abdonominal Pain', 'Bruises', 'Broken Toe', 'Choking', 'Wound', 'Diarrhea', 'Frost bite', 'Heat Exhaustion', 'Heat Stroke', 'Insect Bites', 'nose bleed', 'Pulled Muscle', 'Rectal bleeding', 'Sun Burn', 'Testicle Pain', 'Vertigo', 'Normal Bleeding', 'Eye Injury', 'Chemical Burn', 'Poison'

In [ ]:
for label in labels_lower:
  if output_word == label:
    a = labels_lower.index(label)

print(a)

6


In [ ]:
responses = []
for intent in data['intents']:
  for response in intent['responses']:
    responses.append(response)

print(responses[a])

1)Stop any bleeding. Apply pressure to the wound with a sterile bandage, a clean cloth or a clean piece of clothing. 2)Immobilize the injured area. Don't try to realign the bone or push a bone that's sticking out back in. If you've been trained in how to splint and professional help isn't readily available, apply a splint to the area above and below the fracture sites. Padding the splints can help reduce discomfort. 3)Apply ice packs to limit swelling and help relieve pain. Don't apply ice directly to the skin. Wrap the ice in a towel, piece of cloth or some other material. 4)Treat for shock. If the person feels faint or is breathing in short, rapid breaths, lay the person down with the head slightly lower than the trunk and, if possible, elevate the legs.


In [ ]:
def chat():
  print('Start talking with the bot type quit to stop')
  while True:
    inp = input("You : ")
    if inp.lower() == 'quit':
      break

    next_word = 1

    for _ in range (next_word):
      token_list = tokenizer.texts_to_sequences([inp])[0]
      token_list = pad_sequences([token_list], padding='pre')
      predicted = model.predict_classes(token_list, verbose=0)
      output_word = ""
    for word, index in tokenizer.word_index.items():
      if index == predicted:
        output_word = word
    output_word = stemmer.stem(output_word)
    for label in labels_lower:
      if output_word == label:
        a = labels_lower.index(label)
        break
    print(responses[a])

In [ ]:
chat()

Start talking with the bot type quit to stop
You : How to cure cuts


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


Wash the cut properly to prevent infection and stop the bleeding by applying pressure for 1-2minutes until bleeding stops. Apply Petroleum Jelly to make sure that the wound is moist for quick healing. Finally cover the cut with a sterile bandage. Pain relievers such as acetaminophen can be applied.
You : how to treat a rash
1)Olive oil helps in healing and promotes skin renewal given it is packed with vitamin E and antioxidants. It also soothes the skin and reduces itching. 2)Baking soda is useful in drying skin rashes as also in relieving itching and inflammation. 3)Aloe Vera,Thanks to its antibacterial, antifungal, anti-inflammatory and emollient properties, aloe vera is excellent for treating a number of skin ailments including rashes as also soothing the skin.
You : how to treat a mild headache
Give ibuprofen (Advil, Motrin), aspirin, or acetaminophen (Tylenol) for pain. Avoid ibuprofen and other NSAIDs if the person has heart failure or kidney failure. Do not give aspirin to a chi